// Single source of truth for matchmaking tags
// Used in: NetworkingPreferencesTab, EventProfileTab, NetworkingFilterPopup

export const MATCHMAKING_ROLES = [
  'Founder',
  'Freelancer',
  'HR/Recruiter',
  'Student',
  'Employee (CLT)',
  'Investor',
  'Developer',
  'Designer',
  'Marketing Pro',
  'CEO/Executive',
  'Product Manager',
  'Content Creator',
  'Sales Professional',
  'Engineer',
  'Data Scientist',
  'Operations Manager',
  'Researcher',
  'Lawyer',
  'Accountant',
  'Professor/Teacher',
  'Project Manager',
  'CTO/CIO',
  'COO',
  'CFO',
  'Architect',
  'Journalist',
  'Analyst',
  'Consultant',
];

export const MATCHMAKING_INDUSTRIES = [
  'Software/Tech',
  'Marketing Digital',
  'Fintech',
  'HealthTech',
  'E-commerce',
  'Design/UX',
  'Sales/B2B',
  'Education',
  'Consulting',
  'AgriTech',
  'Gaming/Entertainment',
  'Real Estate/PropTech',
  'Legal/LegalTech',
  'Fashion/Retail',
  'AI/Machine Learning',
  'Cybersecurity',
  'Blockchain/Web3',
  'Logistics/Supply Chain',
  'Food & Beverage',
  'Tourism/Hospitality',
  'Sustainability/CleanTech',
  'Biotech/Pharma',
  'Insurance/InsurTech',
  'Automotive',
  'Telecom',
  'Media/Advertising',
  'HR Tech',
  'Construction/Infrastructure',
  'Sports/Fitness',
  'Non-Profit/NGO',
  'Aerospace/Defense',
  'Energy/Utilities',
];

export const MATCHMAKING_GOALS = [
  'Hiring',
  'Open to Work',
  'Finding Co-founder',
  'Seeking Mentorship',
  'Offering Mentorship',
  'Investing',
  'Just Networking',
  'Learning & Development',
  'Partnership Opportunities',
  'Fundraising',
  'Career Change',
  'Building Community',
  'Selling Products/Services',
  'Finding Clients',
  'Speaker Opportunities',
  'Co-Working/Collaboration',
  'Side Project Partners',
];

export const TAG_LIMITS = {
  professional_roles: 3,
  industries: 3,
  networking_goals: 6,
} as const;
